### ISSUE TITLE
Modifying initialize_proccessing()

### ISSUE THREAD

**Issue by katz-s** [casangi/cngi-io#1]
I built GPU/CPU clusters in a local environment in NAOJ, and modified cngi-io.initialize_processing() to execute test codes on these clusters. It works fine.
So, could I make a branch to add some cluster initializing logic around initialize_proccessing() and issue a PR? I want to add the local methods like the below and modify initialize_proccessing() to call these methods from it as a user needs:

- CPU cluster (Kubernetes/Helm) initializer
- GPU cluster (CUDA 11/cudf/dask_cuda based on RAPIDS.ai) initializer

**Comment by Jan-Willem** [comment]
@katz-s Please go ahead.

**Comment by katz-s** [comment]
@Jan-Willem Thanks! I will do it later.

**Comment by jacobtomlinson** [comment]
Hey there! I saw this issue, hope you don't mind me commenting. I'm a RAPIDS/Dask maintainer and work a bunch on running workloads on Kubernetes. We've done a load of work over the last 18 months to make [dask-kubernetes](https://kubernetes.dask.org/en/latest/) an awesome way to deploy both CPU and GPU clusters on Kubernetes. If I can be of any help to you in getting things set up, or if you have questions and want to chat please let me know.

**Comment by katz-s** [comment]
Hi @jacobtomlinson, I think dask-kubernetes is so cool solution to use dask.distribute on kubernetes easily. Should any questions or problems arise, I would greatly appreciate your advice and support. Thank you for your comment!

**Comment by katz-s** [comment]
Issued PR.
